
from langchain_core.prompts import ChatPromptTemplate,PromptTemplate,HumanMessagePromptTemplate, SystemMessagePromptTemplate,AIMessagePromptTemplate
from pydantic import BaseModel, Field
from openai import OpenAI
from langchain_deepseek import ChatDeepSeek


analysis_prompt = ChatPromptTemplate(
    messages=[SystemMessagePromptTemplate.from_template
              ("You are a professor of forensic pathology specializing in analyzing death cases."),
              HumanMessagePromptTemplate.from_template("""
              
            <Instruction>
            
            Compose a cause-of-death analysis note based on the provided case details.
            It is essential to carefully differentiate between the causative and direct causes of death in forensic investigations. 
            Specifically, determining whether trauma serves as the precipitating factor or the primary cause of death is a critical distinction that requires thorough analysis. 
            This distinction has significant implications for the legal and medical understanding of the case. Therefore, conclusions regarding the cause of death must be drawn with utmost caution, ensuring that all factors, including underlying medical conditions, pre-existing vulnerabilities, and the role of external trauma, are fully considered. 
            Rigorous, evidence-based reasoning is necessary to prevent premature or biased conclusions, as this determination influences both clinical and forensic outcomes.
            
            </Instruction>
            
            <Guidelines for Writing the Analysis Note>
            
            **1. Autopsy Findings**:
            
            Summarize the key pathological features or injuries observed during the autopsy.
            Provide a concise description of the location and nature of these findings (e.g., fractures, tissue damage, organ changes), using 3-4 sentences.
            
            **2. Cause of Death Analysis**:
            
            Analyze the direct or indirect connection between these pathological features or injuries and the cause of death.
            Discuss how external factors (e.g., surgery, accidents, violence) might relate to these injuries or pathological conditions.
            
            **3. Pathological Background and Death Correlation**:
            
            Consider the patient's medical history and lifestyle to discuss how pre-existing health conditions influenced the death.
            Evaluate the role of chronic diseases or existing health issues in the death.
            
            **4. Supplementary Test Results**:
            
            Mention any forensic tests performed (e.g., toxicology, histology).
            Explain how these results support or challenge the preliminary cause of death analysis.
            
            **5. Conclusion and Inference**:
            
            Clearly summarize the relationship between the autopsy findings and the cause of death.
            Provide a final forensic opinion based on a comprehensive analysis of the autopsy and supplementary test results.
            Ensure your analysis is thorough, specific, and clearly outlines the scientific rationale and logical reasoning behind each step.
            
            **6. Additional Instructions**:
            
            The output should be a continuous paragraph without subheadings or bullet points.
            Ensuring the use of precise medical terminology for professional accuracy.
            Maintain objectivity and scientific rigor, avoiding any speculative language (e.g., "might," "likely," "possibly").
            
            
            *** Ensure that the structure, format, and expression match the given Examples as similar as possible.***
            The output should be in Chinese.
            
            </Guidelines for Writing the Analysis Note>        
            
            <Context of this Case>
            
            {context}
            
            </Context of this Case>
            
            <Observed Findings>
            
            {obs_result}
            
            </Observed Findings>
            
            <Supplementary Information>
                                    
            {supplements}
            
            </Supplementary Information>
            
            <Examples>
            
            {fewshot}
            
            </Examples>   
                                 

            
              """)
              ],

)


###

#You need to fill in an example suitable for your local institution in <Example>xxx</Example>.
#Original means to fill in the result generated by the intelligent agent for the first time.
#Revised means to fill in a corresponding result that complies with the specifications.
#The purpose of this step is to make the generated expression more compliant with the requirements of your region.

reanalysis_prompt = ChatPromptTemplate(
    messages=[SystemMessagePromptTemplate.from_template
              ("You are a professor of forensic pathology specializing in analyzing death cases."),
              HumanMessagePromptTemplate.from_template("""

            <Instruction>

            Your task is to enhance the following statement used for a cause-of-death analysis, making it more scientifically rigorous and detailed. 
            First, review the provided example, which illustrates how to make a well-constructed cause-of-death analysis statement(Revised[good example] vs Original[bad example]). 
            Then, revise the given statement with the same level of rigor, particularly focusing on the method of analyzing injury relationships as shown in the example. 
            The revised statement should be in Chinese and limited to 400 words.
            Revised Statements must not contain words such as maybe（可能） or perhaps（也许）.etc.
            Revised Statements must be rigorously affirmative.            
            It is essential to carefully differentiate between the causative and direct causes of death in forensic investigations. 
            Specifically, determining whether trauma serves as the precipitating factor or the primary cause of death is a critical distinction that requires thorough analysis. 
            This distinction has significant implications for the legal and medical understanding of the case. 
            Therefore, conclusions regarding the cause of death must be drawn with utmost caution, ensuring that all factors, including underlying medical conditions, pre-existing vulnerabilities, and the role of external trauma, are fully considered. 
            Rigorous, evidence-based reasoning is necessary to prevent premature or biased conclusions, as this determination influences both clinical and forensic outcomes.

            </Instruction>

            <Example>

            Original: 
            
            xxxx（fill it !）

            Revised:
            
            xxxx（fill it !）

            </Example>

            <This Case>

            Original:

            {context}

            </This Case>


              """)
              ],

)

human_prompt = ChatPromptTemplate(
    messages=[SystemMessagePromptTemplate.from_template
              ("You are a professor of forensic pathology specializing in analyzing death cases."),
              HumanMessagePromptTemplate.from_template("""

            <Instruction>

            Your task is to refine and enhance the following cause-of-death analysis based on existing feedback, making it more scientific, rigorous, and fluent. 
            Please ensure the revised text is written in Chinese and does not exceed 400 characters. 
            You may refer to the example format below for guidance:

            <\Instruction>


            <example>

            {fewshot}

            </example>


            <Original analytical note>

            {context}

             <\Original analytical note>

            <human feedback>

            {human}

            </human feedback>


              """)
              ],

)

conclusion_prompt = ChatPromptTemplate(
    messages=[SystemMessagePromptTemplate.from_template
              ("You are a professor of forensic pathology specializing in analyzing death cases."),
              HumanMessagePromptTemplate.from_template("""

            <Instruction>

             Your task is to select the most appropriate conclusion from a set of candidate conclusions based on a detailed analysis of the case. Follow these steps:

             1. **Review the Analysis**: Carefully read and understand the provided analysis of the case, focusing on the key facts, evidence, and findings.
             2. **Evaluate Candidate Conclusions**: Assess each candidate conclusion against the analysis. Identify which conclusion most accurately aligns with the evidence and facts presented.
             3. **Formulate the Final Conclusion**: Choose the candidate conclusion that best explains the cause of death in a clear, concise, and definitive manner. Avoid any speculative language (e.g., "may," "might," "could").
             4. **Language Requirement**: Provide your final conclusion in Chinese.

            </Instruction>

            <Analysis of the Case>

             {context}

            </Analysis of the Case>

            <Candidate Conclusions>


            {candicate}


            </Candidate Conclusions>



              """)
              ],

)





class Analytical_note(BaseModel):
    """ Complete content of the analytical note (Refer to similar examples of expression whenever possible.)"""

    analytical_note: str = Field(description="analytical note of the given case")

class Analytical_revised(BaseModel):
    """ Complete content of the Revised analytical note """

    Revised: str = Field(description="Revised Statement of analytical note,The presentation should be scientifically rigorous and fluent.")


class Conclusion_analysis(BaseModel):
    """ Content of the analytical conclusion """

    analytical_con: str = Field(description="analytical conclusion,usually one short sentence.")


model= ChatDeepSeek(model="deepseek-chat",temperature=0)


## Collaborative Summarization

structured_llm_analysis = model.with_structured_output(Analytical_note)
analysis_chain = analysis_prompt | structured_llm_analysis


structured_llm_revised = model.with_structured_output(Analytical_revised)
reanalysis_chain = reanalysis_prompt | structured_llm_revised


## human-in-the-loop

human_chain = human_prompt | structured_llm_revised



## conclusion

structured_llm_conclusion = model.with_structured_output(Conclusion_analysis)
conclusion_chain = conclusion_prompt | structured_llm_conclusion




#####  local Forensic-LLM

def conclusion(ana):
    client = OpenAI(api_key="EMPTY", base_url="http://0.0.0.0:8002/v1/")
    tmp = ana +"\n 请根据此分析说明总结鉴定意见"
    messages = [{"role": "system", "content": "你是一个经验丰富的法医病理医生。"},
                {"role": "user", "content": tmp}
                ]
    l_conclusion=[]
    for i in range(30):
        response = client.chat.completions.create(
            model="zhenyuan",
            messages=messages,
            stream=False,
        )
        l_conclusion.append(response.choices[0].message.content)
    return l_conclusion
